name: frontend
description: "A new Flutter project."

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  http: ^1.2.2
  provider: ^6.0.0 
  flutter_localizations:
    sdk: flutter
  jwt_decoder: ^2.0.1
  file_picker: ^8.1.2  # Add file_picker package
  csv: ^6.0.0          # Add csv package
  mailto: ^2.0.0       # Add mailto package for email functionality
  url_launcher: ^6.1.7 # Add url_launcher package for launching email client
  fl_chart: ^0.69.0
  intl: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
